# Generated by Django 3.0.3 on 2020-04-21 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialWidgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=1000, upload_to='media/')),
                ('postTitle', models.CharField(max_length=100)),
                ('postBody', models.CharField(max_length=280)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
