# Generated by Django 3.0.3 on 2020-04-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialWidgets', '0004_auto_20200422_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgFilter',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
