# Generated by Django 3.0.3 on 2020-04-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialWidgets', '0005_post_imgfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgFilter',
            field=models.CharField(default='noFilter', max_length=50),
        ),
    ]
