# Generated by Django 3.0.3 on 2020-04-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialWidgets', '0006_auto_20200424_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
