# Generated by Django 3.0.3 on 2020-04-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialWidgets', '0008_auto_20200424_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zipCode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
