# Generated by Django 3.0.3 on 2020-04-26 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialWidgets', '0009_user_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('complete', 'complete'), ('incomplete', 'incomplete')], default='incomplete', max_length=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noteOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
