# Generated by Django 3.0.3 on 2020-04-30 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialWidgets', '0010_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=600)),
                ('commentedPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentedPost', to='socialWidgets.Post')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commenter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
